name: Build and Deploy Backend

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  backend:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build
        build-root-directory: ./backend/
    - name: SFTP Upload
      uses: Dylan700/sftp-upload-action@v1.2.0
      with:
        server: ${{secrets.SSH_HOST}} 
        username: ${{secrets.SSH_USERNAME}}
        key: ${{secrets.SSH_KEY}}
        uploads: |
          ./backend/build/libs => backend/
        delete: true
