name: Build and Deploy Backend

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  backend:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build
        build-root-directory: ./backend/
    - name: SFTP
      uses: swillner/sftp-sync-action@v1.0
      with:
        server: ${{secrets.SSH_HOST}} 
        user: ${{secrets.SSH_USERNAME}}
        user_private_key: ${{secrets.SSH_KEY}}
        local: ./backend/build/libs/*
        remote: ./backend/

  frontend:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'
    - run: npm i
      working-directory: frontend
    - run: npm run build --if-present
      working-directory: frontend
    - name: SFTP
      uses: swillner/sftp-sync-action@v1.0
      with:
        server: ${{secrets.SSH_HOST}} 
        user: ${{secrets.SSH_USERNAME}}
        user_private_key: ${{secrets.SSH_KEY}}
        local: ./frontend/dist/*
        remote: ./frontend/
