name: Build and Deploy Backend

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build
        build-root-directory: /backend/
    - name: SFTP Push
      uses: datanomi/SFTP-Push@v.1.2.2.1h
      with:
        username: ${{ secrets.SSH_USERNAME }}
        server: ${{ secrets.SSH_HOST }}
        port: 22
        ssh_private_key: ${{ secrets.SSH_KEY }} 
        local_path: /backend/build/libs/Banking-ktor-all.jar
        remote_path: ~/backend/
